env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules: {}
globals:
  process: true
overrides:
  - files:
    - "**/*.test.js"
    env:
      jest: true

